CREATE DATABASE user_service;
GRANT ALL PRIVILEGES ON DATABASE users TO postgres;
CREATE DATABASE monitor;
GRANT ALL PRIVILEGES ON DATABASE monitor TO postgres;
CREATE DATABASE postgres;
GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;
CREATE DATABASE messages;
GRANT ALL PRIVILEGES ON DATABASE messages TO postgres;