CREATE DATABASE user_service;
GRANT ALL PRIVILEGES ON DATABASE users TO postgres;
CREATE DATABASE monitor;
GRANT ALL PRIVILEGES ON DATABASE monitor TO postgres;
CREATE DATABASE goods;
GRANT ALL PRIVILEGES ON DATABASE goods TO postgres;
CREATE DATABASE messages;
GRANT ALL PRIVILEGES ON DATABASE messages TO postgres;