version: '3'
    
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  goods:
    build: ./goods
    command: bash -c "python goods/manage.py makemigrations && python goods/manage.py migrate && python goods/manage.py loaddata tag.json && python goods/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db