version: '3'

networks:
  app-tier:
    driver: bridge


services:
  db:
    image: postgres
    restart: always
    build:
      context: .
      dockerfile: ./pg_init/Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/posgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-tier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: 'bitnami/redis:latest'
    ports:
    - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier

  rabbit:
    image: "rabbitmq:3-management"
    hostname: rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: "TESTVOLUME"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-tier
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log

  mail:
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: smtp.yandex.ru
      RELAY_PORT: 587
      RELAY_USERNAME: username
      RELAY_PASSWORD: password
    networks:
      - app-tier

  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=guest
      - AMQP_PASSWORD=guest
      - AMQP_HOST=rabbit
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbit
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"
    depends_on:
      - rabbit
      - db
    networks:
      - app-tier
  
  goods:
    build: goods/
    command: bash -c "python goods/manage.py makemigrations && python goods/manage.py migrate && python goods/manage.py loaddata tag.json && python goods/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-tier

  user_service:
    build: ./user_service
    command: bash -c "python3 user_service/app/server.py"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - app-tier

  messages:
    build: ./messages
    command: bash -c "uvicorn messages.app.asgi:app --reload --host 0.0.0.0 --port 8008"
    volumes:
      - .:/code
    ports:
      - "8008:8008"
    depends_on:
      - db
    networks:
      - app-tier

  monitor_service:
    build: ./monitor_service
    command: bash -c "uvicorn monitor_service.app.asgi:app --reload --host 0.0.0.0 --port 8888"
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    depends_on:
      - db
      - rabbit
      - worker
    networks:
      - app-tier

  worker:
    build:
      context: ./monitor_service
      dockerfile: ./celery.Dockerfile
    depends_on:
      - rabbit
      - db
    networks:
      - app-tier

volumes:
  rabbit:
    driver: local
  postgres_data: