# Generated by Django 3.0.8 on 2020-08-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Название тега")),
            ],
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.UUIDField(default=0)),
                (
                    "title",
                    models.CharField(max_length=60, verbose_name="Название объявления"),
                ),
                ("description", models.TextField(verbose_name="Описание объявления")),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                ("img_src", models.FileField(null=True, upload_to="items")),
                (
                    "views",
                    models.PositiveIntegerField(
                        auto_created=True, default=0, editable=False
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="goods.Tags",
                    ),
                ),
            ],
        ),
    ]
