"""add stat table

Revision ID: c152acc3da27
Revises: 
Create Date: 2020-08-12 15:42:24.394536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c152acc3da27"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stats",
        sa.Column("UUID", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("service", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column(
            "response_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "request_timestamp",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("UUID"),
        sa.UniqueConstraint("UUID"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stats")
    # ### end Alembic commands ###
