"""add stats table

Revision ID: c33f852453c7
Revises: 
Create Date: 2020-08-28 19:27:27.932115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c33f852453c7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stats",
        sa.Column("UUID", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("service", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_time", sa.Float(), nullable=True),
        sa.Column("request_timestamp", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("UUID"),
        sa.UniqueConstraint("UUID"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stats")
    # ### end Alembic commands ###
