# Generated by Django 3.0.8 on 2020-07-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
    ]
