# Generated by Django 3.0.8 on 2020-07-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20200714_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
