# Generated by Django 3.0.8 on 2020-07-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60, verbose_name='Название объявления')),
                ('description', models.TextField(verbose_name='Описание объявления')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('tag', models.IntegerField(choices=[(1, 'Транспорт'), (2, 'Личные вещи'), (3, 'Для дома и дачи'), (4, 'Бытовая электроника'), (5, 'Хобби и отдых'), (6, 'Недвижимость'), (7, 'Работа'), (8, 'Услуги'), (9, 'Для бизнеса'), (10, 'Животные')], verbose_name='Тип объявления')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('img_src', models.FileField(upload_to='items')),
            ],
        ),
    ]
